/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f401xx.h"
#include "gpio.h"
#include "i2c.h"

uint8_t tx = 0x01;
uint8_t len = sizeof(tx);
volatile uint8_t tx_done = 0;
volatile uint8_t tx_phase = 0;
volatile uint8_t rx_flag = 0;

#define TX_LEN    0
#define TX_DATA   1

#define SLAVE_ADDR 0x55

void Delay(void){for(volatile uint32_t i = 0; i < 200000; i++);}
void sDelay(void){for(volatile uint32_t i = 0; i < 100000; i++);}

void LED_Init(void){
    GPIO_Handle_t led;
    led.pGPIOx = GPIOC;
    GPIO_ClockControl(GPIOC, ENABLE);

    led.GPIOx_CFG.pin_number     = GPIO_PIN_13;
    led.GPIOx_CFG.pin_mode       = GPIO_MODE_OUT;
    led.GPIOx_CFG.pin_op_type    = GPIO_OUT_PP;
    led.GPIOx_CFG.pin_pu_pd_ctrl = GPIO_NO_PUPD;
    led.GPIOx_CFG.pin_speed      = GPIO_OSPEED_HIGH;

    GPIO_Init(&led);
    GPIO_WritePin(GPIOC, GPIO_PIN_13, SET);
}

void I2C2_GPIO_Init(void){
    GPIO_Handle_t i2c_gpio;
    i2c_gpio.pGPIOx = GPIOB;
    GPIO_ClockControl(GPIOB, ENABLE);

    i2c_gpio.GPIOx_CFG.pin_mode = GPIO_MODE_ALT_FN;
    i2c_gpio.GPIOx_CFG.pin_op_type = GPIO_OUT_OPDRN;
    i2c_gpio.GPIOx_CFG.pin_speed = GPIO_OSPEED_HIGH;
    i2c_gpio.GPIOx_CFG.pin_pu_pd_ctrl = GPIO_PIN_PU;

    //SDA
    i2c_gpio.GPIOx_CFG.pin_alt_func_mode = 9;
    i2c_gpio.GPIOx_CFG.pin_number = GPIO_PIN_3;
    GPIO_Init(&i2c_gpio);

    //SCL
    i2c_gpio.GPIOx_CFG.pin_alt_func_mode = 4;
    i2c_gpio.GPIOx_CFG.pin_number = GPIO_PIN_10;
    GPIO_Init(&i2c_gpio);
}

I2C_Handle_t i2c2;

void I2C2_EV_IRQHandler(void) {
	I2C_IRQ_EV_Handler(&i2c2);
}
void I2C2_ER_IRQHandler(void) {
	I2C_IRQ_ER_Handler(&i2c2);
}

void I2C2_Init(void){
    i2c2.pI2Cx = I2C2;
    I2C_ClockControl(I2C2, ENABLE);

    i2c2.I2C_Config.I2C_DeviseAddress = SLAVE_ADDR;
    i2c2.I2C_Config.I2C_AckControl = I2C_ACK_ENABLE;
    i2c2.I2C_Config.I2C_SCLSpeed = I2C_SCL_SPEED_SM;
    i2c2.I2C_Config.I2C_FMDutyCycle = I2C_FM_DUTY_2;

    I2C_Init(&i2c2);
}


void I2C_ApplicationEventCallback(I2C_Handle_t *pI2C_Handle, uint8_t event){
    if(event == I2C_EV_ADDR_MATCH){
        rx_flag = 1;

    }else if(event == I2C_EV_DATA_REQ){
        if(tx_done == 0){
            I2C_Slave_Transmit(I2C2, len);
            tx_done = 1;
        }else{
            I2C_Slave_Transmit(I2C2, tx);
            tx_done = 0;
            rx_flag = 2;
        }

    }else if(event == I2C_EV_STOP){
        tx_done = 0;
        rx_flag = 3;
    }else if(event == I2C_ERROR_AF){
        tx_done = 0;
        rx_flag = 4;
    }
}

void I2C_Slave_EnableInterrupts(I2C_REG_t *pI2Cx){
    pI2Cx->CR2 |= (1 << I2C_CR2_ITEVTEN);
    pI2Cx->CR2 |= (1 << I2C_CR2_ITBUFEN);
    pI2Cx->CR2 |= (1 << I2C_CR2_ITERREN);
}

int main(void){
    LED_Init();
    I2C2_GPIO_Init();
    I2C2_Init();

    I2C_IRQ_InterruptConfig(IRQ_NO_I2C2_EV, ENABLE);
    I2C_IRQ_InterruptConfig(IRQ_NO_I2C2_ER, ENABLE);

    I2C_PeripheralControl(I2C2, ENABLE);
    I2C_AckControl(I2C2, I2C_ACK_ENABLE);

    I2C_Slave_EnableInterrupts(I2C2);

    GPIO_WritePin(GPIOC, GPIO_PIN_13, RESET);
        Delay();
        GPIO_WritePin(GPIOC, GPIO_PIN_13, SET);
        Delay();

    while(1){
    	if(rx_flag == 1){

    		GPIO_WritePin(GPIOC, GPIO_PIN_13, RESET);
    		Delay();
    		GPIO_WritePin(GPIOC, GPIO_PIN_13, SET);
    		Delay();

    		rx_flag = 0;
    	}else if(rx_flag >= 2){
    	   uint8_t blinks = rx_flag;
    	   rx_flag = 0;
    	   for(uint32_t i = 0; i < blinks; i++){
    	    GPIO_WritePin(GPIOC, GPIO_PIN_13, RESET);
    	    Delay();
    	    GPIO_WritePin(GPIOC, GPIO_PIN_13, SET);
    	    Delay();
    	   }
    	}
    }
}
